### ISSUE TITLE
library source does not match byte code

### ISSUE THREAD

**Issue by augla** [grasshopper7/cucumber-pdf-report#10]
When linking cucumber-pdf-report 1.7.0 in Intellij and for example going to ReportData I get the warning that the library source does not match the byte code, and indeed when looking at the decompiled class, something goes wrong with publication of the sources of this library.

**Comment by grasshopper7** [comment]
Have added a new version in maven. Try and let me know. plugin version 1.3.0 will get the latest 2.0.0 version of the report.
