### ISSUE TITLE
Can't Generate PDF report at all

### ISSUE THREAD

**Issue by GoldenGuts** [grasshopper7/cucumber-pdf-report#13]
I tried to generate the report using JSON, as you said. But I am unable to generate any report even with the example project you have on github it's not working. What is happening?

**Comment by grasshopper7** [comment]
Are u getting an error? Which sample project did u use? adapters or plugin?

**Comment by GoldenGuts** [comment]
I used the plugin one, https://github.com/grasshopper7/cucumber-pdf-plugin-report 
no error, just no pdf generated... logs just said passed the test

**Comment by grasshopper7** [comment]
Have added a new version in maven. Try and let me know.
