### ISSUE TITLE
Ability to hide Tags summary from the generated PDF

### ISSUE THREAD

**Issue by prtraj2** [grasshopper7/cucumber-pdf-report#41]
Need another configuration in the pdf-config.yaml to skip generating Tags summary section in the PDF report. I didn't find any configuration to hide the same. 

I am able to skip generation of feature summary and scenario summary sections in the PDF by setting the displayFeature and displayScenario as false in the pdf-config.yaml. So if we can have one flag/ config like **displayTag** and if set as false should not generate the tags summary in the report.

**Comment by prtraj2** [comment]
Hi @grasshopper7, did you get a chance to look at this feature request? Thanks.

**Comment by grasshopper7** [comment]
Added in version 2.11.0
